version: "2"
services:
  acquire-frontend:
    build: .
    environment: 
      PATH: ./node_modules/.bin:$PATH
    container_name: acquire-frontend
    ports:
      - "8080:8080"
    volumes:
     - .:/usr/share/nginx/html/acquire-frontend
    command: ash -c "npm install && npm run dev"    
